notifications:
  slack: cuencafinance:q2niGnIOrMjr2skYrp2W3L0f

language: python

script: make test

jobs:
  include:
    - stage: test
      python: 3.6
    - stage: test
      python: 3.7
      dist: xenial
      sudo: true